import numpy as np
import statsmodels.api as sm
spector_data = sm.datasets.spector.load(as_pandas=False)
spector_data.exog = sm.add_constant(spector_data.exog, prepend=False)
x = np.array([1, 2, 3, 4, 5])
X = np.column_stack((x, x**2))
X = sm.add_constant(X)
print(X)
print(X.shape)
beta = np.array([1, 0.1, 10])
#y = np.dot(X, beta)
y = np.array([4, 6, 4, 5, 5])
print(y)
mod = sm.OLS(y, X)
res = mod.fit()
print(res.summary())
print('Parameters: ', res.params)
print('R2: ', res.rsquared)
